@startuml
Celery -> TASK: Celery создает таск
TASK -> CLIENT: Таск дерагет клиента
CLIENT -> SEVER: Клиент отправляет данные на сервер \nиспользуя web-сокеты и IP адрес сервера для подключения \n (SANIC)
SEVER -> DICT: Запихивает данные в словарь, \nгде ключом является ID клиента, \nкоторому эти данные предназначаются
DICT -> SEVER
SEVER-> CLIENT2: При запросе клиента с\n нужным ID данные вытаскиваются\n из DICT и отправляются ему
@enduml