version: '3'

services:

  shortlink:
    image: registry.gitlab.com/garpix/microservices/microservice_empty_python:${microservice_empty_pythontag}
    command: sh -c "/code/conf/run.sh"
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./public:/code/public

  postgres:
    image: postgres:10-alpine
    restart: always
    env_file:
      - .env
    volumes:
    - ./postgres/data:/var/lib/postgresql/data
    - ./postgres/dumps:/dumps

